# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextLine.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets


class Text(QtWidgets.QTextEdit):            #为TextEdit控件添加拖拽效果
    def __init__(self,parent):
        super(Text, self).__init__(parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, e):
        if e.mimeData().hasText():
            e.accept()
        else:
            e.ignore()

    def dropEvent(self, e):
        file_dir = e.mimeData().text()[8:]
        try:
            f = open(file_dir,'r')
            lines = f.read()
        except:
            print("Error")
        self.clear()
        self.setText(lines)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 867)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.register_text = QtWidgets.QTextEdit(self.centralwidget)
        self.register_text.setGeometry(QtCore.QRect(791, 235, 171, 498))
        self.register_text.setStatusTip("")
        self.register_text.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhMultiLine)
        self.register_text.setObjectName("register_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1030, 70, 36, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.mem_text = QtWidgets.QTextEdit(self.centralwidget)
        self.mem_text.setGeometry(QtCore.QRect(969, 235, 171, 498))
        self.mem_text.setObjectName("mem_text")
        self.set_mem = QtWidgets.QPushButton(self.centralwidget)
        self.set_mem.setGeometry(QtCore.QRect(980, 140, 150, 80))
        self.set_mem.setIconSize(QtCore.QSize(20, 200))
        self.set_mem.setObjectName("set_mem")
        self.set_reg = QtWidgets.QPushButton(self.centralwidget)
        self.set_reg.setGeometry(QtCore.QRect(800, 140, 150, 80))
        self.set_reg.setObjectName("set_reg")
        self.state_text = QtWidgets.QLineEdit(self.centralwidget)
        self.state_text.setGeometry(QtCore.QRect(969, 90, 171, 40))
        self.state_text.setAlignment(QtCore.Qt.AlignCenter)
        self.state_text.setObjectName("state_text")
        self.run_botton = QtWidgets.QPushButton(self.centralwidget)
        self.run_botton.setGeometry(QtCore.QRect(550, 40, 161, 28))
        self.run_botton.setObjectName("run_botton")
        self.pc_text = QtWidgets.QLineEdit(self.centralwidget)
        self.pc_text.setGeometry(QtCore.QRect(791, 90, 171, 40))
        self.pc_text.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_text.setObjectName("pc_text")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 70, 18, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.right_picture = QtWidgets.QLabel(self.centralwidget)
        self.right_picture.setGeometry(QtCore.QRect(780, -30, 471, 891))
        self.right_picture.setText("")
        self.right_picture.setObjectName("right_picture")
        self.file_picture = QtWidgets.QLabel(self.centralwidget)
        self.file_picture.setGeometry(QtCore.QRect(40, 90, 731, 641))
        self.file_picture.setText("")
        self.file_picture.setObjectName("file_picture")
        self.left_picture = QtWidgets.QLabel(self.centralwidget)
        self.left_picture.setGeometry(QtCore.QRect(0, -30, 780, 891))
        self.left_picture.setText("")
        self.left_picture.setObjectName("left_picture")
        self.file_text = Text(self.centralwidget)
        self.file_text.setGeometry(QtCore.QRect(40, 90, 731, 641))
        self.file_text.setStatusTip("")
        self.file_text.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhMultiLine)
        self.file_text.setObjectName("file_text")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 40, 211, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pos_botton = QtWidgets.QPushButton(self.widget)
        self.pos_botton.setObjectName("pos_botton")
        self.horizontalLayout.addWidget(self.pos_botton)
        self.pos_input = QtWidgets.QLineEdit(self.widget)
        self.pos_input.setObjectName("pos_input")
        self.horizontalLayout.addWidget(self.pos_input)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.fontselect = QtWidgets.QAction(MainWindow)
        self.fontselect.setObjectName("fontselect")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.fontselect)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Y86模拟器"))
        self.label_2.setText(_translate("MainWindow", "STAT"))
        self.set_mem.setText(_translate("MainWindow", "显示/隐藏内存"))
        self.set_reg.setText(_translate("MainWindow", "显示/隐藏寄存器值"))
        self.run_botton.setText(_translate("MainWindow", "运行下一条指令"))
        self.label.setText(_translate("MainWindow", "PC"))
        self.pos_botton.setText(_translate("MainWindow", "运行至指定位置处"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.fontselect.setText(_translate("MainWindow", "字体"))
